2023-06-23 22:28:01,140 INFO ReactPy preloader has detected component frontend.src.components.login.loginForm
2023-06-23 22:28:01,375 DEBUG ReactPy has registered component frontend.src.components.login.loginForm
2023-06-23 22:28:01,375 INFO ReactPy preloader has detected component frontend.src.components.register.newMember
2023-06-23 22:28:01,379 DEBUG ReactPy has registered component frontend.src.components.register.newMember
2023-06-23 22:28:01,379 INFO ReactPy preloader has detected component frontend.src.components.register.registerFamily
2023-06-23 22:28:01,379 DEBUG ReactPy has registered component frontend.src.components.register.registerFamily
2023-06-23 22:28:01,379 INFO ReactPy preloader has detected component frontend.src.components.profile.UserProfile
2023-06-23 22:28:01,381 DEBUG ReactPy has registered component frontend.src.components.profile.UserProfile
2023-06-23 22:28:01,441 ERROR ReactPy websocket authentication has failed!
Traceback (most recent call last):
  File "C:\Users\Tevin\Documents\life_pieces\personal\nostalgia\nostalgia\lib\site-packages\channels\auth.py", line 95, in login
    backend = backend or user.backend
  File "C:\Users\Tevin\Documents\life_pieces\personal\nostalgia\nostalgia\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'Member' object has no attribute 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tevin\Documents\life_pieces\personal\nostalgia\nostalgia\lib\site-packages\reactpy_django\websocket\consumer.py", line 37, in connect
    await login(self.scope, user)
  File "C:\Users\Tevin\Documents\life_pieces\personal\nostalgia\nostalgia\lib\site-packages\asgiref\sync.py", line 479, in __call__
    ret: _R = await loop.run_in_executor(
  File "C:\Users\Tevin\anaconda3\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Tevin\Documents\life_pieces\personal\nostalgia\nostalgia\lib\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Tevin\Documents\life_pieces\personal\nostalgia\nostalgia\lib\site-packages\asgiref\sync.py", line 538, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Tevin\Documents\life_pieces\personal\nostalgia\nostalgia\lib\site-packages\channels\auth.py", line 101, in login
    raise ValueError(
ValueError: You have multiple authentication backends configured and therefore must provide the `backend` argument or set the `backend` attribute on the user.
2023-06-23 22:28:01,471 WARNING ReactPy has detected component sessions in the database, but no timestamp was found in cache. This may indicate that the cache has been cleared.
